name: Discuss "help-wanted" PR on Discord
on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - if: ${{ github.event.label.name == 'help wanted' }}
        name: Discuss on Discord-PR (Non-maintainer only)
        uses: EndBug/discuss-on-discord@v1.1.0
        with:
          destination: ${{ secrets.DISCORD_BOT_DESTINATION }}
          discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_message: New PR created in `${{ github.repository }}`:<https://github.com/${{
            github.repository }}/pull/${{ github.event.pull_request_number || github.event.pull_request.number
            }}>
          issue_comment: "Hey \U0001F44B, I've just created a [thread]($THREAD_LINK$)\
            \ for this pull request on [PyTorch-Ignite Discord](https://pytorch-ignite.ai/chat)\
            \ where you can quickly talk to the community on the topic."
          issue_number: ${{ github.event.inputs.pull_request_number || github.event.pull_request.number
            }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740223510.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740223510.json
permissions:
  pull-requests: write
