name: Run Horovod tests
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: hvd-tests-${{ github.ref_name }}-${{ !(github.ref_protected) || github.sha}}
jobs:
  horovod-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - id: get-date
        name: Get year & week number
        run: echo "date=$(/bin/date "+%Y-%U")" >> $GITHUB_OUTPUT
        shell: bash -l {0}
      - id: measurement-3
        name: Record Measurement After Get year & week number
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get year & week number
          task: get-measurement
      - id: pip-cache
        name: Get pip cache dir
        run: 'python3 -m pip install -U pip

          echo "pip_cache=$(python3 -m pip cache dir)" >> $GITHUB_OUTPUT

          '
        shell: bash -l {0}
      - id: measurement-5
        name: Record Measurement After Get pip cache dir
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get pip cache dir
          task: get-measurement
      - uses: actions/cache@v3
        with:
          key:
            ${{ steps.get-date.outputs.date }}-horovod-${{ hashFiles('requirements-dev.txt')
            }}
          path: "~/conda_pkgs_dir

            ${{ steps.pip-cache.outputs.pip_cache }}

            "
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          "\n#install other dependencies\npip install torch torchvision --index-url\
          \ https://download.pytorch.org/whl/cpu\npip install -r requirements-dev.txt\n\
          \n# Install Horovod from source and apply a patch to build with recent pytorch\n\
          # We can't use pip install <whatever> as build-env can't find pytorch and\
          \ \n# `--no-build-isolation` does not work with horovod setup.py\ngit clone\
          \ --recursive https://github.com/horovod/horovod.git /tmp/horovod\ncd /tmp/horovod\n\
          sed -i \"s/CMAKE_CXX_STANDARD 14/CMAKE_CXX_STANDARD 17/g\" CMakeLists.txt\n\
          sed -i \"s/CMAKE_CXX_STANDARD 14/CMAKE_CXX_STANDARD 17/g\" horovod/torch/CMakeLists.txt\
          \          \nHOROVOD_WITH_PYTORCH=1 python setup.py install            \
          \    \ncd -\n# test the installation:\npython -c \"import horovod.torch\
          \ as hvd; hvd.mpi_ops.Sum\"\n\n# Install ignite\npython setup.py install\n"
        shell: bash -l {0}
      - id: measurement-9
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Download MNIST
        uses: pytorch-ignite/download-mnist-github-action@master
        with:
          target_dir: /tmp
      - name: Run Tests
        uses: nick-fields/retry@v3
        with:
          command: bash tests/run_cpu_tests.sh
          max_attempts: 5
          new_command_on_retry: USE_LAST_FAILED=1 bash tests/run_cpu_tests.sh
          shell: bash
          timeout_minutes: 15
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          file: ./coverage.xml
          flags: hvd-cpu
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740223535.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740223535.json
    strategy:
      matrix:
        python-version:
          - "3.11"
        pytorch-channel:
          - pytorch
    timeout-minutes: 60
