name: PyTorch version tests
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - id: get-date
        name: Get year & week number
        run: echo "date=$(/bin/date "+%Y-%U")" >> $GITHUB_OUTPUT
        shell: bash -l {0}
      - id: measurement-3
        name: Record Measurement After Get year & week number
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get year & week number
          task: get-measurement
      - id: pip-cache
        name: Get pip cache dir
        run: 'python3 -m pip install -U pip

          echo "pip_cache=$(python3 -m pip cache dir)" >> $GITHUB_OUTPUT

          '
        shell: bash -l {0}
      - id: measurement-5
        name: Record Measurement After Get pip cache dir
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get pip cache dir
          task: get-measurement
      - uses: actions/cache@v3
        with:
          key:
            ${{ steps.get-date.outputs.date }}-pytorch-${{ runner.os }}-${{ matrix.python-version
            }}-${{ matrix.pytorch-version }}-${{ hashFiles('requirements-dev.txt')
            }}
          path: "~/conda_pkgs_dir

            ${{ steps.pip-cache.outputs.pip_cache }}

            "
          restore-keys:
            "${{ steps.get-date.outputs.date }}-pytorch-${{ runner.os
            }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-

            "
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
      - name: Install dependencies
        run:
          "conda install pytorch=${{ matrix.pytorch-version }} torchvision cpuonly\
          \ python=${{ matrix.python-version }} -c pytorch\n\n# We should install\
          \ numpy<2.0 for pytorch<2.3\nnumpy_one_pth_version=$(python -c \"import\
          \ torch; print(float('.'.join(torch.__version__.split('.')[:2])) < 2.3)\"\
          )\nif [ \"${numpy_one_pth_version}\" == \"True\" ]; then\n  pip install\
          \ -U \"numpy<2.0\"\nfi\n\npip install -r requirements-dev.txt\npython setup.py\
          \ install\n\n# pytorch>=1.9.0,<1.11.0 is using \"from setuptools import\
          \ distutils; distutils.version.LooseVersion\" anti-pattern\n# which raises\
          \ the error: AttributeError: module 'distutils' has no attribute 'version'\
          \ for setuptools>59\nbad_pth_version=$(python -c \"import torch; print('.'.join(torch.__version__.split('.')[:2])\
          \ in ['1.9', '1.10'])\")\nif [ \"${bad_pth_version}\" == \"True\" ]; then\n\
          \  pip install --upgrade \"setuptools<59\"\n  python -c \"from setuptools\
          \ import distutils; distutils.version.LooseVersion\"\nfi\n"
        shell: bash -l {0}
      - id: measurement-9
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Download MNIST
        uses: pytorch-ignite/download-mnist-github-action@master
        with:
          target_dir: /tmp
      - name: Run Tests
        uses: nick-fields/retry@v3
        with:
          command: bash -l tests/run_cpu_tests.sh "not test_time_profilers"
          max_attempts: 5
          new_command_on_retry:
            USE_LAST_FAILED=1 bash -l tests/run_cpu_tests.sh "not
            test_time_profilers"
          shell: bash
          timeout_minutes: 15
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740223534.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740223534.json
    strategy:
      fail-fast: false
      matrix:
        exclude:
          - python-version: "3.10"
            pytorch-version: 1.10.0
          - python-version: "3.11"
            pytorch-version: 1.10.0
          - python-version: "3.10"
            pytorch-version: 1.11.0
          - python-version: "3.11"
            pytorch-version: 1.11.0
          - python-version: "3.11"
            pytorch-version: 1.12.1
          - python-version: "3.11"
            pytorch-version: 1.13.1
        python-version:
          - 3.9
          - "3.10"
          - "3.11"
        pytorch-version:
          - 2.5.1
          - 2.4.1
          - 2.3.1
          - 2.2.2
          - 1.13.1
          - 1.12.1
          - 1.10.0
      max-parallel: 5
    timeout-minutes: 85
  create-issue:
    if: always() && needs.build.result == 'failure'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create issue if pytorch version tests failed
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/failed_schedule_issue_template.md
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740223534.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740223534.json
