name: PyPI Stable Releases
on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: "3.10"
      - name: Install dependencies
        run: "conda install -y pytorch torchvision cpuonly -c pytorch

          pip install -r requirements-dev.txt

          "
        shell: bash -l {0}
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Build and Publish PyPI binaries
        run: '# workaround to fix https://github.com/pytorch/ignite/issues/2373

          pip uninstall -y twine pkginfo

          pip install --upgrade --no-cache-dir twine ''pkginfo>=1.8.2''

          python setup.py sdist bdist_wheel

          twine --version

          twine check dist/*

          TWINE_USERNAME="${{ secrets.PYPI_USER }}" TWINE_PASSWORD="${{ secrets.PYPI_TOKEN
          }}" twine upload --verbose dist/*

          '
        shell: bash -l {0}
      - id: measurement-6
        name: Record Measurement After Build and Publish PyPI binaries
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build and Publish PyPI binaries
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740223534.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740223534.json
