name: Anaconda Stable Releases
on:
  push:
    branches:
      - main

jobs:
  conda-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: '3.10'
      - name: Install dependencies
        run: 'conda install -y pytorch torchvision cpuonly -c pytorch

          python setup.py install

          '
        shell: bash -l {0}
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          UPLOAD_USER: pytorch
        name: Build and Publish Conda binaries
        run: 'chmod +x ./conda.recipe/build_and_upload.sh

          ./conda.recipe/build_and_upload.sh

          '
        shell: bash -l {0}
      - id: measurement-6
        name: Record Measurement After Build and Publish Conda binaries
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build and Publish Conda binaries
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740223534.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740223534.json
